- id: check-sonar-quality-gate
  name: Check SonarQube Quality Gate
  entry: python scripts/sonar_checks.py
  language: system # Add more if your script needs it
  additional_dependencies: [requests]
  pass_filenames: false
  verbose: true
